### ISSUE TITLE
Undefined use of replaying when USE_REPLAY is disabled. 

### ISSUE THREAD

**Issue by Ryzee119** [NagyD/SDLPoP#241]
Small regression from commit https://github.com/NagyD/SDLPoP/commit/9047166ada13169f5aa3e27fdd117539731bc084

Now causes this when USE_REPLAY is disabled.
`seg007.c:881:9: error: use of undeclared identifier 'replaying'`

Here
https://github.com/NagyD/SDLPoP/blob/9047166ada13169f5aa3e27fdd117539731bc084/src/seg007.c#L881

replaying variable is only initalised under a `#ifdef USE_REPLAY` which causes this issue.

**Comment by NagyD** [comment]
Fixed: d49637546a1b8a515861b883ac4047e968fcea76
